# Generated by Django 5.1.1 on 2024-10-04 17:33

import django.core.validators
import django.db.models.deletion
import worldOfSpeed.cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rally', 'Rally'), ('open-wheel', 'Open-wheel'), ('kart', 'Kart'), ('drag', 'Drag'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)])),
                ('year', models.IntegerField(validators=[worldOfSpeed.cars.validators.validate_year_value])),
                ('image_url', models.URLField(unique=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
